# Generated by Django 4.0.5 on 2022-07-22 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cook_for_kids', '0004_alter_holiday_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='text',
            field=models.CharField(default='free', max_length=30),
        ),
    ]
