# Generated by Django 4.0.5 on 2022-07-22 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cook_for_kids', '0005_alter_holiday_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notdays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('kid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cook_for_kids.kid')),
            ],
        ),
    ]
