# Generated by Django 4.0.5 on 2022-07-30 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cook_for_kids', '0009_remove_kid_notday_notday_kid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Waiverday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('kid', models.ManyToManyField(related_name='waiverdaykids', to='cook_for_kids.kid')),
            ],
        ),
        migrations.DeleteModel(
            name='Notday',
        ),
    ]
