# Generated by Django 4.0.5 on 2025-04-28 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cook_for_kids', '0010_waiverday_delete_notday'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='waiverday',
            options={'ordering': ['-date']},
        ),
        migrations.RemoveField(
            model_name='kid',
            name='score',
        ),
        migrations.AlterField(
            model_name='dish',
            name='dish_name',
            field=models.CharField(max_length=500),
        ),
    ]
