# Generated by Django 4.0.5 on 2025-07-30 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cook_for_kids', '0012_globalsettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='globalsettings',
            options={'verbose_name': 'Global Settings', 'verbose_name_plural': 'Global Settings'},
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='excursion_day',
            field=models.IntegerField(blank=True, choices=[(None, 'No weekly excursion'), (0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday')], default=1, help_text='Day of the week for excursions (leave empty for no weekly excursion)', null=True),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='weekly_event_text',
            field=models.CharField(default='Essen to go (Ausflugsessen)', help_text='Text to display for weekly excursion meals', max_length=100),
        ),
    ]
