# Generated by Django 4.0.5 on 2022-07-14 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kochlischda', '0003_alter_holiday_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='text',
            field=models.CharField(default='2022-07-14', max_length=30),
        ),
    ]
