# Generated by Django 4.0.5 on 2022-07-23 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kochlischda', '0007_notday_delete_notdays'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notday',
            name='kid',
        ),
        migrations.AddField(
            model_name='kid',
            name='notday',
            field=models.ManyToManyField(related_name='notdaykids', to='kochlischda.notday'),
        ),
    ]
